[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lava_presale = "5fYyn9ZN1bFEbqjZvLMMqibSBKZTdvWTWrtKLnWqALbj"

[programs.localnet]
lava_programs = "FyB2J5z75o5bE9Ts9McZR6inuWyzpNGCKjFgBFtWAkLm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/matt5XJ1oeuMSJeLM5aXi2kJUkGqfzFPWDBjCwTcvoN.json"

[scripts]
test = "pnpm exec jest --preset ts-jest"
